export const S1 = [
  {id:1,taskOrder:1,name:"Bistro Tile 24k Gold Accent Halloween Vanity Tray",rating:2.7,price:40,image:"/photo1.jpg"},
  {id:2,taskOrder:2,name:"HydroJug x Anthropologie 40 oz. Traveler Water Bottle",rating:7.7,price:44.99,image:"/photo2.jpg"},
  {id:3,taskOrder:3,name:"Bubble Initial and Pear-Cut Stone Necklace",rating:7.6,price:48,image:"/photo3.jpg"},
  {id:4,taskOrder:4,name:"Textured Scrunchies, Set of 3",rating:8.6,price:32,image:"/photo4.jpg"},
  {id:5,taskOrder:5,name:"HydroJug 32 oz. Traveler Water Bottle",rating:8.6,price:34.99,image:"/photo5.jpg"},
  {id:6,taskOrder:6,name:"HydroJug x Anthropologie 32 oz. Traveler Water Bottle",rating:2.6,price:39.99,image:"/photo6.jpg"},
  {id:7,taskOrder:7,name:"'47 MLB Mini Logo Baseball Cap",rating:8.7,price:42,image:"/photo7.jpg"},
  {id:8,taskOrder:8,name:"Gemstone Huggie Hoop Earrings",rating:8.5,price:34,image:"/photo8.jpg"},
  {id:9,taskOrder:9,name:"Crystal Initial Pendant Necklace",rating:5.5,price:44,image:"/photo9.jpg"},
  {id:10,taskOrder:10,name:"Bezel Stone Ring",rating:9.1,price:63.99,image:"/photo10.jpg"},
  {id:11,taskOrder:11,name:"Crystal Baguette Ring",rating:7.1,price:50.83,image:"/photo11.jpg"},
  {id:12,taskOrder:12,name:"HydroJug x Anthropologie 32 oz. Traveler Water Bottle",rating:8.1,price:39.99,image:"/photo12.jpg"},
  {id:13,taskOrder:13,name:"PHLUR Afterglow Eau de Parfum",rating:8.2,price:61,image:"/photo13.jpg"},
  {id:14,taskOrder:14,name:"VERB Ghost Icons Kit",rating:4.1,price:55,image:"/photo14.jpg"},
  {id:15,taskOrder:15,name:"Living Proof Scalp Care Exfoliator",rating:4.6,price:42,image:"/photo15.jpg"},
  {id:16,taskOrder:16,name:"Deborah Pagani The Vital Mist Heat Protectant Frizz Control Hair Essence",rating:4.1,price:69,image:"/photo16.jpg"},
  {id:17,taskOrder:17,name:"Sachajuan Clarifying Scalp Scrub",rating:2.9,price:58,image:"/photo17.jpg"},
  {id:18,taskOrder:18,name:"Bohemian Wildflower Body Scrub",rating:6.5,price:34,image:"/photo18.jpg"},
  {id:19,taskOrder:19,name:"Crosley Cruiser Plus Turntable",rating:4.5,price:68,image:"/photo19.jpg"},
  {id:20,taskOrder:20,name:"Abstract Print Hair Scarves, Set of 2",rating:7.3,price:34,image:"/photo20.jpg"},
  {id:21,taskOrder:21,name:"Iris Pressed Glass Vase",rating:7.3,price:52,image:"/photo21.jpg"},
  {id:22,taskOrder:22,name:"Initial Stretch Rings, Set of 3",rating:9.5,price:54,image:"/photo22.jpg"},
  {id:23,taskOrder:23,name:"Statement Stone Bracelet",rating:6.4,price:44,image:"/photo23.jpg"},
  {id:24,taskOrder:24,name:"HydroJug Slim Can Cooler",rating:2.7,price:24.99,image:"/photo24.jpg"},
  {id:25,taskOrder:25,name:"Abbode Waffle Cosmetic Bag",rating:6.2,price:68,image:"/photo25.jpg"},
  {id:26,taskOrder:26,name:"Anastasia Beverly Hills Lip Gloss",rating:2.2,price:23,image:"/photo26.jpg"},
  {id:27,taskOrder:27,name:"Wonderskin Wonder Blading All-Day Lip Stain",rating:6.2,price:22,image:"/photo27.jpg"},
  {id:28,taskOrder:28,name:"maison millais Eau De Parfum",rating:5.5,price:71,image:"/photo28.jpg"},
  {id:29,taskOrder:29,name:"SALT & STONE Bergamot & Hinoki Body Mist",rating:5.9,price:45,image:"/photo29.jpg"},
  {id:30,taskOrder:30,name:"Supergoop! Destination Glow SPF Kit",rating:5.5,price:36,image:"/photo30.jpg"},
  {id:31,taskOrder:31,name:"Cluster Studded Belt",rating:5.5,price:53,image:"/photo31.jpg"},
  {id:32,taskOrder:32,name:"Vismaya 100% Silk Hair Scarf",rating:5.8,price:48,image:"/photo32.jpg"},
  {id:33,taskOrder:33,name:"Fiona Beaded Trinket Dish",rating:5.6,price:22.4,image:"/photo33.jpg"},
  {id:34,taskOrder:34,name:"By Anthropologie Floral Drop Earrings",rating:5.8,price:44,image:"/photo34.jpg"},
  {id:35,taskOrder:35,name:"Molly Hatch Halloween Trinket Dish",rating:5.8,price:18,image:"/photo35.jpg"},
  {id:36,taskOrder:36,name:"Resin Bangles, Set of 3",rating:8.8,price:48,image:"/photo36.jpg"},
  {id:37,taskOrder:37,name:"The Blake Skinny Belt",rating:8.8,price:32,image:"/photo37.jpg"},
  {id:38,taskOrder:38,name:"Hydro Flask Micro Hydro 200 ML Water Bottle",rating:8.8,price:22.95,image:"/photo38.jpg"},
  {id:39,taskOrder:39,name:"Sonia Mini Slouchy Tote Bag",rating:4.8,price:40.99,image:"/photo39.jpg"},
  {id:40,taskOrder:40,name:"Sonix Antimicrobial iPhone Case",rating:2.7,price:40,image:"/photo40.jpg"}
];
